### ISSUE TITLE
Advanced 2

### ISSUE THREAD

**Issue by fr8nkL** [khwang0/2018F-COMP3111#33]
Since the requirement only asks us to restore List<Item> instead of ObservableList<ItemData>, I was wondering whether it means that we can absolutely ignore the post date and time and how should other functionalities concerning the post date and time behave, for instance latest post in Summary.

**Comment by comp3111ta** [comment]
Theoretically speaking...

If you have implemented somethings in your feature without considering other students piece. You might end up with full marks and your groupmate might fail to achieve full marks. This might not be applicable in your example but would be nice to be aware of. 

Of course, if that data is only useful in some features that your group does not sign up for, you can discard it without doubt.

**Comment by fr8nkL** [comment]
Sorry for bothering again but I was wondering what the functionality of loading the file. The requirement just asks for the console display of the loaded data. Are we expected to redo other tasks such as summary, table, distribution, etc. with respect to the loaded data?

**Comment by comp3111ta** [comment]
Yes. You got the point. 

You need to make the screen "consistent". Same principle applies to other feature like Refine / Last Search

**Comment by fr8nkL** [comment]
Thank you for your reply. In this sense, I think the requirement has made some comments wrong. The requirement only asks to restore List<Item>. Now we have to restore ObservableList<ItemData>. What is more confusing is that the class ItemData class does not even have a function for us to restore its postedDate. I was wondering what the exact requirement is, especially regarding to tasks involving the posted date and time.

**Comment by Wongky** [comment]
> > Are we expected to redo other tasks such as summary, table, distribution, etc. with respect to the loaded data?
> 
> You need to make the screen "consistent". Same principle applies to other feature like Refine / Last Search

This implies basic5,basic6,advance2 have to use the function in basic1, basic4,advance1,advance3.

#26 

>how do we grade the unit test is by functions (class-function, not feature-function). 

> We will ask you to declare which class-function would involve your feature. Then we will compute the coverage for those functions only. What if a class-function is shared by multiple group members? They are counted multiple times.

So, the unit test and coverage test for function in basic1, basic4,advance1,advance3 is also counted to people who implement basic5,basic6,advance2?
But it is the responsibility for people who implement basic1, basic4,advance1,advance3 to ensure their code work well.

**Comment by comp3111ta** [comment]
The coverage test does not carry forward in this case.  The responaibility
chains cut at you CALL the update function of those tabs.

However if the update function does not work.  You cant help,  not your
fault.    Make sure you call the function with correct parameters,  if
applicable.
